export const SET_POKEMONS = 'SET_POKEMONS';
export const SET_POKEMONS_WITH_DETAILS = 'SET_POKEMONS_WITH_DETAILS';
export const SET_COMPARE_POKEMONS = 'SET_COMPARE_POKEMONS';
export const CLEAN_COMPARE_POKEMONS = 'CLEAN_COMPARE_POKEMONS';
export const DELETE_POKEMON_FROM_COMPARE = 'DELETE_POKEMON_FROM_COMPARE';